// File generated by gen-offsets
//
// $ avr-ld --version
// GNU ld version 2.14.90 20040216
// $ avr-gcc --version
// avr-gcc (GCC) 3.5.0 20040216 (experimental)

#define CONTEXT_STATE 0
#define CONTEXT_STACK_PTR 1
#define CONTEXT_NEXT 3
#define CONTEXT_TIMEOUT 5
#define CONTEXT_WAITING_FOR 7
#define CONTEXT_NEXT_WAITING 9
#define CONTEXT_PREV_WAITING 11
#define CONTEXT_STACK_END 13
#define CONTEXT_MIN_STACK_PTR 15
