#!/bin/sh

VERSION="mk_ada_app 0.2"

#   Copyright (c) 2006 Bernd Trog <berndtrog@yahoo.com>
# 
#   This program is free software; you can redistribute it and/or Modify
#   it under the terms of the GNU General Public License as published By
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#

echo -e "$VERSION\n"

if [ $# -ne 4 ]; then
exit
   echo "Usage:"
   echo "sh mk_ada_app.sh Directory_Name project_name main_package_name mcu_name"
   echo "Note: project_name, main_package_name, mcu_name have to be lower case!"
   echo "Example:"
   echo "sh mk_ada_app.sh 6_Channel_DVM dvm dvm_main atmega8"
   exit 1;
fi;

function dirnameX()
{
  local dir="${1%${1##*/}}"
  [ "${dir:=./}" != "/" ] && dir="${dir%?}"
  echo "$dir"
}

DATA_DIR=`dirnameX $0`/../mk_ada_app

directory=$1
project=$2
package=$3
mcu=$4

echo "directory: \"$directory\""
echo "  project: \"$project\""
echo "  package: \"$package\""
echo 
 
if [ ! -e "$directory" ]; then
    echo "Creating directory \"$directory\".."
    mkdir "$directory"
    
    echo "Preprocessing start files.."
    avr-gnatprep  -Dproject=$project "$DATA_DIR/start.ads" "$directory/$project.ads"
    avr-gnatprep  -Dproject=$project -Dpackage=$package "$DATA_DIR/start.adb" \
       "$directory/$project.adb"
    
    echo "Preprocessing main package files.."
    avr-gnatprep  -Dpackage=$package "$DATA_DIR/package.adb" "$directory/$package.adb"
    avr-gnatprep  -Dpackage=$package "$DATA_DIR/package.ads" "$directory/$package.ads"
    
    echo "Creating Makefile.."
    echo "MCU := $mcu" >"$directory/Makefile"
    echo "ADA_TARGETS := $project" >>"$directory/Makefile"
    cat "$DATA_DIR/Makefile.prep" >>"$directory/Makefile"

    echo "Creating $project.gpr file.."
    avr-gnatprep  -Dproject=$project -Dsrc_project=\"$project\" \
        -Dpackage=$package "$DATA_DIR/prj.gpr" "$directory/$project.gpr"
    echo -e "\n\n\n\n--  generated by $VERSION" >>"$directory/$project.gpr"
    echo -e "\nDone. (Now, try 'make -C \"$directory\"')"
else
    echo "I won't overwrite an existing directory \"$directory\"."
fi;
